### PR TITLE
has_contract() : Determine whether a account deploied contract

### PR DESCRIPTION
**Pull request by wirtecode**
**Change Description**

bool has_contract() : Determine whether to deploy the contract

**Consensus Changes**

**API Changes**

**Documentation Additions**

### CODE REVIEW

**Review by vlbos — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Approved.

**Review by michaeljyeates — COMMENTED** [review]
The function comment is wrong in transaction.h, Should be something like "Tests if the account has an installed contract"

In wasm_interface, should `(has_contract,           int(int64_t)             )` be `(has_contract,           int(int8_t)             )` because it is returning a boolean?

Text in the printcode demo is incorrect

**Comment by kesar** [comment]
> In wasm_interface, should (has_contract, int(int64_t) ) be (has_contract, int(int8_t) ) because it is returning a boolean?

I had same feeling when I saw it, but all previous code for booleans is using int64_t, not sure if there is a real reason.

**Comment by wirtecode** [comment]
The comment is really inaccurate。

bool has_contract(account_name name)  //  account_name is int64_t

**Comment by wirtecode** [comment]
> > In wasm_interface, should (has_contract, int(int64_t) ) be (has_contract, int(int8_t) ) because it is returning a boolean?
> 
> I had same feeling when I saw it, but all previous code for booleans is using int64_t, not sure if there is a real reason.

The comment is really inaccurate。

bool has_contract(account_name name) // account_name is int64_t

**Comment by wirtecode** [comment]
> > In wasm_interface, should (has_contract, int(int64_t) ) be (has_contract, int(int8_t) ) because it is returning a boolean?
> 
> I had same feeling when I saw it, but all previous code for booleans is using int64_t, not sure if there is a real reason.

The comment is really incorrect, sorry.
bool has_contract(account_name name) // account_name is 64bit

**Pull request merged**
